//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheSstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int idOrder { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public int idProduct_Size { get; set; }
        public string Size { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product_Size Product_Size { get; set; }
    }
}
