//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheSstore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_Size
    {
        public int idProduct_Size { get; set; }
        public int idProduct { get; set; }
        public int idSize { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lượng tồn")]
        public int quantity { get; set; }
        public bool quantityinstock { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
