//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheSstore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Size = new HashSet<Product_Size>();
        }
    
        public int idProduct { get; set; }
        public string codeProduct { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string nameProduct { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mô tả (nhập 'không' hoặc bất kỳ từ nào khác)")]
        public string describe { get; set; }
        public string thumb { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public int quantity { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá tiền")]
        public double price { get; set; }
        public int idProductCategory { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn ngày cập nhật")]
        public System.DateTime updateDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Size> Product_Size { get; set; }
    }
}
